export const en = {
  appName: "Aiba",
  phases: {
    morning: {
      title: "Morning",
      action: "Plan",
      phaseLabel: "PLANNING",
      tagline: "Set today's main goal and up to three tasks.",
      kanji: "朝",
    },
    afternoon: {
      title: "Afternoon",
      action: "Focus",
      phaseLabel: "FOCUS",
      tagline: "Work on one task with a timer.",
      kanji: "午",
    },
    evening: {
      title: "Evening",
      action: "Unwind",
      phaseLabel: "UNWIND",
      tagline: "Note what went well and your first step for tomorrow.",
      kanji: "夕",
    },
  },
  messages: {
    morning: [
      "What matters most today?",
      "One main goal. Up to three tasks.",
      "Plan lightly — start focus when ready.",
    ],
    afternoon: [
      "Pick one task and start the timer.",
      "One session at a time.",
      "Stay with what you chose.",
    ],
    evening: [
      "Wrap up the day.",
      "What went well?",
      "Note tomorrow's first step.",
    ],
    focusing: [
      "Stay with your task.",
      "Focus session is running.",
      "One task. One timer.",
    ],
    recovery: [
      "Step away from the screen.",
      "Take a short break.",
      "Breathe before you continue.",
    ],
    review: [
      "How did that session feel?",
      "Save it or skip.",
      "Wrap up when ready.",
    ],
    help: [
      "Tap a question below.",
      "I can explain any section.",
      "Try a suggested question.",
    ],
  },
  eventMessages: {
    sessionStarted: "Focus is on. I'll stay quiet.",
    sessionPaused: "Paused. Resume when you're ready.",
    sessionFinished: "Session complete. Take a break.",
    reviewSaved: "Saved to Sessions.",
    shutdownComplete: "Day wrapped up. Rest well.",
    firstTask: "Add one task — that's your starting point.",
    firstFocus:
      "Tap Start focus on a task in Plan, then press Begin when ready.",
    firstShutdown: "Write one thing that went well and tomorrow's first step.",
  },
  preview: "Previewing this rhythm.",
  expand: "Expand",
  minimize: "Minimize",
  hideWidget: "Hide widget",
  loading: "Loading…",
  sessionDone: "Session finished",
  singleTask: "Current task",
  flowCheck: "How was the session?",
  recovery: "Break",
  askAiba: "Ask Aiba",
  askNoMatch: "I can explain planning, focus, notes, sessions, and settings.",
  gotIt: "Got it",
  aria: {
    phaseNav: "Day phase",
    focusCycle: "Focus session",
    reducedMotion: "Enable reduced motion",
    tunnelVision: "Enable screen dimming",
    deepWorkGuard: "Enable focus mode",
    blockSites: "Enable site blocking during focus",
  },
  taskTypes: {
    deep: "Deep work",
    shallow: "Light tasks",
    learning: "Learning",
    collab: "Collaboration",
  },
  nav: {
    today: "Today",
    notes: "Quick notes",
    sessions: "Sessions",
    preferences: "Preferences",
  },
  navDescriptions: {
    today: "Your phase view: plan tasks, run a focus session, or unwind.",
    notes: "Capture thoughts without changing your task list.",
    sessions: "Past focus sessions and patterns.",
    preferences: "Theme, language, guard, and motion.",
  },
  settingsGroups: {
    profile: "Profile",
    appearance: "Appearance",
    focus: "Focus environment",
    sites: "Site blocking",
    links: "Shortcuts",
  },
  settingDescriptions: {
    displayName: "Shown in the sidebar greeting.",
    appearance: "Choose light or dark for the whole app.",
    language: "Updates all labels, buttons, and messages immediately.",
    reducedMotion:
      "Turns off Aiba’s hair and head motion, timer arc motion, panel slide-in, toast pop-in, and the focusing status pulse.",
    tunnelVision: "Dims the rest of the screen while a focus session runs.",
    deepWorkGuard:
      "When you press Begin, turns on focus helpers (e.g. quiet notifications). It does not edit the hosts file or ask for admin — that only happens if you apply site blocking in Preferences.",
    blockSites: "Shows the domain list and manual apply/remove controls.",
    domains:
      "One hostname per line. Applied only when you click Apply site block.",
    openWindowsFocus:
      "Opens Windows Settings → System → Notifications. Turn on Do not disturb and configure Focus (Concentración) for quiet sessions.",
    openFocusGuide: "Opens the break rhythm reference in a separate window.",
  },
  empty: {
    priorities: "No tasks yet. Add one line to get started.",
    sessionsNone: "No sessions yet. Finish a focus session to see it here.",
    sessionsEarly:
      "Sessions appear below. Patterns unlock after three completed sessions.",
    notes: "Anything pulling at your attention? Write it here.",
    shutdown: "One line about today is enough.",
  },
  actions: {
    startFocus: "Start focus",
    planToday: "Today's plan",
    wrapUp: "Unwind",
    takeBreak: "Take a break",
    fineTune: "Adjust difficulty",
    openStudio: "Expand",
    saveSession: "Save session",
    completeShutdown: "Finish for today",
    begin: "Begin",
    pause: "Pause",
    resume: "Resume",
    finish: "Finish",
    confirmFinish: "Tap again to finish",
    skip: "Skip",
    discard: "Discard",
    recoveryComplete: "Recovery complete",
    openHelp: "Open help",
    goThere: "Go there",
    clearAsk: "Clear Ask Aiba",
    clearCompleted: "Clear completed",
    saveTask: "Save",
    cancelEdit: "Cancel",
  },
  labels: {
    mainGoal: "Today's main goal",
    mainGoalHint: "What should be done by end of day?",
    mainGoalPlaceholder: "e.g. Finish the project outline",
    tasks: "Tasks (up to 3)",
    addTaskPlaceholder: "Add a task…",
    newTask: "New task",
    editTask: "Edit task",
    deleteTask: "Delete task",
    applySiteBlock: "Apply site block now",
    removeSiteBlock: "Remove site block",
    restoreDefaultSites: "Restore default list",
    removeSiteBlockHint:
      "Remove clears Aiba's hosts entries. Always available — use it if a site stays blocked after closing the app.",
    siteBlockHint:
      "One hostname per line. Blocks while you focus (if enabled) or immediately when you click Apply. Cleared when focus ends, when you hide/quit Aiba, and again on next launch if anything was left behind.",
    displayName: "Your name",
    displayNamePlaceholder: "e.g. Alex",
    focusOutput: "What are you working on?",
    focusOutputPlaceholder: "e.g. Write the first draft",
    duration: "Duration (minutes)",
    unwindWentWell: "What went well today?",
    unwindTomorrow: "First step for tomorrow",
    unwindTomorrowPlaceholder: "e.g. Review notes at 9am",
    heroTask: "Main task",
    tasksRemaining: (n) => `${n} task${n === 1 ? "" : "s"} remaining today`,
    timeLeft: (m) => `${m}m left`,
    skill: "Skill",
    challenge: "Challenge",
    depth: "Depth",
    language: "Language",
    appearance: "Appearance",
    themeDark: "Dark",
    themeLight: "Light",
    reducedMotion: "Reduced motion",
    tunnelVision: "Dim screen",
    deepWorkGuard: "Focus mode",
    blockSites: "Block listed sites during focus",
    domains: "Domains, one per line",
    openWindowsFocus: "Open Do not disturb & Focus",
    openFocusGuide: "Open focus guide",
    sessionDisposition: "Session disposition",
    done: "Done",
    continueLater: "Continue later",
    nextAction: "Next concrete action",
    bestFocusHour: "Best focus hour",
    bestTaskType: "Best task type",
    averageDepth: "Average depth",
    completionRate: "Completion rate",
    domainsPlaceholder: "youtube.com\nx.com",
    sessionMinutes: (n) => `${n} min`,
  },
  language: {
    en: "English",
    es: "Español",
  },
  compact: {
    focusing: "Focusing",
    paused: "Paused",
    recovery: "Break",
    ready: "Ready",
    currentPath: "Current task",
    versionLabel: "AIBA v1.2",
    preferences: "Preferences",
  },
  focus: {
    completed: "Completed",
    completedDuring: (duration) => `Completed during session · ${duration}`,
    currentFocus: "Current focus",
    upNext: "Up next",
    pending: "Pending",
    skillLow: "Low",
    skillMedium: "Medium",
    skillHigh: "High",
    current: "Current",
    markComplete: (task) => `Mark ${task} complete`,
    historyLine: (time, task, skill, challenge, isCurrent) =>
      `${time} — ${task} [Skill: ${skill} / Challenge: ${challenge}]${isCurrent ? " [Current]" : ""}`,
    flowAligned: "Challenge and skill are aligned.",
    flowAnxiety: "Break the output into a smaller milestone.",
    flowBoredom: "Increase the challenge or tighten the output.",
    recoveryHint:
      "Step away from the screen. Walk, stretch, or look into the distance.",
  },
  focusPrep: {
    title: "Start focus",
    emptyLead:
      "Pick a task in Plan and tap Start focus to set up your session here.",
    directLead:
      "Type what you'll work on, or go to Plan to pick from your tasks.",
    goToPlan: "Go to Plan",
    selectedTask: "Working on",
    changeTask: "Change task",
    duration: "Duration",
    durationMin: (n) => `${n} min`,
    taskType: "Task type",
    taskTypeHint:
      "Deep work, light tasks, learning, or collaboration — used in session patterns.",
    environment: "Focus setup",
    preferencesLink: "Preferences",
  },
  review: {
    title: "How was the session?",
    hint: "Helps calculate your focus patterns over time.",
    quality: {
      distracted: "Distracted",
      shallow: "Shallow",
      normal: "Normal",
      deep: "Deep",
    },
    save: "Save session",
    goUnwind: "Note tomorrow in Unwind →",
    nextActionPlaceholder: "Next step (optional)",
  },
  plan: {
    tomorrowPrompt: (step) => `From Unwind: “${step}”`,
    addTomorrowStep: "Add as task",
    dismissTomorrow: "Not now",
    tomorrowHint:
      "Unwind notes are not added to Plan automatically — use this if you want it as a task.",
  },
  patterns: {
    bestHourEmpty: "Need 3 sessions starting at the same hour.",
    bestTypeEmpty: "Need 3 sessions of the same task type.",
  },
  ask: {
    intro: "Tap a question for a short answer.",
    faqs: [
      { id: "morning-plan", question: "What is Plan for?" },
      { id: "afternoon-focus", question: "How do I start a focus block?" },
      { id: "evening-unwind", question: "What do I write in Unwind?" },
      { id: "sessions", question: "Where can I see past sessions?" },
      { id: "preferences", question: "What can I change in Preferences?" },
      { id: "patterns", question: "When do patterns show up?" },
    ],
    openTool: (label) => `Go to ${label} →`,
    openHelp: "Open help →",
  },
  doneToday: "Done today",
  unwind: {
    sessionsToday: "Sessions today",
    focusMinutes: "Focus time",
    tasksCompleted: "Tasks done",
  },
  studio: {
    title: "Aiba",
    coreIntent: "Today's goal",
    atelier: "Compact",
    viewAll: "View all",
    backToPlan: "Back to Plan",
    backToPhase: "Back",
    helloFallback: "Hello",
    helloUser: (name) => `Hello, ${name}`,
    phaseHeader: {
      morning: "Plan",
      afternoon: "Focus",
      evening: "Unwind",
    },
    todayLead: "Today's goal",
    todayPlaceholder: "What should be done today?",
    notesLabel: "Notes",
    notesPlaceholder: "Reminders, open loops, anything on your mind",
    focusLead: "Today's goal",
    unwindLead: "End of day",
    focusTagline: "One task at a time.",
    restTagline: "Take a break when the timer ends.",
    eveningHeadline: "Wrap up",
    sections: {
      today: { jp: "今日", label: "Today" },
      notes: { jp: "控え", label: "Quick notes" },
      tasks: { jp: "事", label: "Tasks" },
      history: { jp: "履歴", label: "History" },
      wentWell: { jp: "良", label: "What went well" },
      tomorrow: { jp: "明日", label: "Tomorrow's first step" },
    },
  },
  toast: {
    siteBlockApplied: "Site block is active.",
    siteBlockRemoved: "Site block removed.",
    defaultSitesRestored: "Default domain list restored.",
    reducedMotionOn: "Reduced motion is on.",
    reducedMotionOff: "Reduced motion is off.",
    tunnelVisionOn: "Screen dimming will apply during focus.",
    tunnelVisionOff: "Screen dimming is off.",
    deepWorkGuardOn: "Focus mode is ready for your next session.",
    deepWorkGuardOff: "Focus mode is off.",
    blockSitesOn: "Domain list shown below. Click Apply to block.",
    blockSitesOff: "Site blocking options hidden.",
    themeDark: "Dark theme applied.",
    themeLight: "Light theme applied.",
  },
  guard: {
    active:
      "Focus guard is on. Turn on Windows Focus to silence notifications.",
    cleanup:
      "Guard stopped, but site-block cleanup needs administrator approval.",
    blockerFailed:
      "Site blocker was not applied. Basic guard remains available.",
    sitesBlocked: "Listed sites are blocked during this focus session.",
    helperRunning: "Site blocker helper is running.",
  },
};
