export const es = {
  appName: "Aiba",
  phases: {
    morning: {
      title: "Mañana",
      action: "Plan",
      phaseLabel: "PLANIFICAR",
      tagline: "Define el objetivo del día y hasta tres tareas.",
      kanji: "朝",
    },
    afternoon: {
      title: "Tarde",
      action: "Focus",
      phaseLabel: "ENFOQUE",
      tagline: "Trabaja en una tarea con un temporizador.",
      kanji: "午",
    },
    evening: {
      title: "Noche",
      action: "Unwind",
      phaseLabel: "DESCANSO",
      tagline: "Anota qué salió bien y el primer paso para mañana.",
      kanji: "夕",
    },
  },
  messages: {
    morning: [
      "¿Qué importa más hoy?",
      "Un objetivo principal. Hasta tres tareas.",
      "Planifica con calma — empieza el enfoque cuando estés listo.",
    ],
    afternoon: [
      "Elige una tarea e inicia el temporizador.",
      "Una sesión a la vez.",
      "Mantente en lo que elegiste.",
    ],
    evening: [
      "Cierra el día.",
      "¿Qué salió bien?",
      "Anota el primer paso de mañana.",
    ],
    focusing: [
      "Quédate con tu tarea.",
      "La sesión de enfoque está activa.",
      "Una tarea. Un temporizador.",
    ],
    recovery: [
      "Aparta la mirada de la pantalla.",
      "Toma un descanso breve.",
      "Respira antes de continuar.",
    ],
    review: [
      "¿Cómo se sintió esa sesión?",
      "Guárdala u omítela.",
      "Cierra cuando quieras.",
    ],
    help: [
      "Toca una pregunta abajo.",
      "Puedo explicar cualquier sección.",
      "Prueba una sugerencia.",
    ],
  },
  eventMessages: {
    sessionStarted: "Enfoque activo. Me quedaré en silencio.",
    sessionPaused: "En pausa. Reanuda cuando quieras.",
    sessionFinished: "Sesión completa. Toma un descanso.",
    reviewSaved: "Guardado en Sesiones.",
    shutdownComplete: "Día cerrado. Descansa bien.",
    firstTask: "Añade una tarea — ese es tu punto de partida.",
    firstFocus:
      "Pulsa Iniciar enfoque en una tarea de Plan y luego Comenzar cuando estés listo.",
    firstShutdown:
      "Escribe una cosa que salió bien y el primer paso de mañana.",
  },
  preview: "Vista previa de este ritmo.",
  expand: "Expandir",
  minimize: "Minimizar",
  hideWidget: "Ocultar widget",
  loading: "Cargando…",
  sessionDone: "Sesión terminada",
  singleTask: "Tarea actual",
  flowCheck: "¿Qué tal fue la sesión?",
  recovery: "Descanso",
  askAiba: "Pregunta a Aiba",
  askNoMatch:
    "Puedo explicar planificación, enfoque, notas, sesiones y ajustes.",
  gotIt: "Entendido",
  aria: {
    phaseNav: "Fase del día",
    focusCycle: "Sesión de enfoque",
    reducedMotion: "Activar movimiento reducido",
    tunnelVision: "Activar atenuación de pantalla",
    deepWorkGuard: "Activar modo concentración",
    blockSites: "Activar bloqueo de sitios durante el enfoque",
  },
  taskTypes: {
    deep: "Trabajo profundo",
    shallow: "Tareas ligeras",
    learning: "Aprendizaje",
    collab: "Colaboración",
  },
  nav: {
    today: "Hoy",
    notes: "Notas rápidas",
    sessions: "Sesiones",
    preferences: "Preferencias",
  },
  navDescriptions: {
    today: "Tu vista por fase: planificar, enfocar o cerrar el día.",
    notes: "Captura ideas sin cambiar tu lista de tareas.",
    sessions: "Sesiones pasadas y patrones.",
    preferences: "Tema, idioma, concentración y movimiento.",
  },
  settingsGroups: {
    profile: "Perfil",
    appearance: "Apariencia",
    focus: "Entorno de enfoque",
    sites: "Bloqueo de sitios",
    links: "Accesos directos",
  },
  settingDescriptions: {
    displayName: "Aparece en el saludo de la barra lateral.",
    appearance: "Elige tema claro u oscuro para toda la app.",
    language: "Actualiza etiquetas, botones y mensajes al instante.",
    reducedMotion:
      "Desactiva el movimiento del cabello y la cabeza de Aiba, la animación del arco del temporizador, la entrada de paneles, el pop-in de avisos y el pulso del estado de enfoque.",
    tunnelVision:
      "Atenúa el resto de la pantalla durante una sesión de enfoque.",
    deepWorkGuard:
      "Al pulsar Comenzar, activa ayudas de concentración (p. ej. silenciar avisos). No toca el archivo hosts ni pide permiso de administrador — eso solo pasa si aplicas bloqueo de sitios en Preferencias.",
    blockSites:
      "Muestra la lista de dominios y los controles de aplicar/quitar.",
    domains: "Un dominio por línea. Solo se aplica al pulsar Aplicar bloqueo.",
    openWindowsFocus:
      "Abre Configuración → Sistema → Notificaciones. Activa No molestar y ajusta Concentración para sesiones sin interrupciones.",
    openFocusGuide: "Abre la guía de descansos en una ventana aparte.",
  },
  empty: {
    priorities: "Aún no hay tareas. Añade una línea para empezar.",
    sessionsNone:
      "Aún no hay sesiones. Termina una sesión de enfoque para verla aquí.",
    sessionsEarly:
      "Las sesiones aparecen abajo. Los patrones se desbloquean tras tres sesiones.",
    notes: "¿Algo que te distraiga? Escríbelo aquí.",
    shutdown: "Una línea sobre hoy es suficiente.",
  },
  actions: {
    startFocus: "Iniciar enfoque",
    planToday: "Plan de hoy",
    wrapUp: "Cerrar día",
    takeBreak: "Tomar descanso",
    fineTune: "Ajustar dificultad",
    openStudio: "Expandir",
    saveSession: "Guardar sesión",
    completeShutdown: "Terminar por hoy",
    begin: "Comenzar",
    pause: "Pausar",
    resume: "Reanudar",
    finish: "Terminar",
    confirmFinish: "Pulsa otra vez para terminar",
    skip: "Omitir",
    discard: "Descartar",
    recoveryComplete: "Descanso completo",
    openHelp: "Abrir ayuda",
    goThere: "Ir allí",
    clearAsk: "Limpiar Pregunta a Aiba",
    clearCompleted: "Limpiar completadas",
    saveTask: "Guardar",
    cancelEdit: "Cancelar",
  },
  labels: {
    mainGoal: "Objetivo principal de hoy",
    mainGoalHint: "¿Qué debería estar hecho al final del día?",
    mainGoalPlaceholder: "p. ej. Terminar el esquema del proyecto",
    tasks: "Tareas (hasta 3)",
    addTaskPlaceholder: "Añadir tarea…",
    newTask: "Nueva tarea",
    editTask: "Editar tarea",
    deleteTask: "Eliminar tarea",
    applySiteBlock: "Aplicar bloqueo ahora",
    removeSiteBlock: "Quitar bloqueo",
    restoreDefaultSites: "Restaurar lista predeterminada",
    removeSiteBlockHint:
      "Primero aplica el bloqueo. Usa Quitar bloqueo para deshacer los cambios en el archivo hosts.",
    siteBlockHint:
      "El bloqueo solo se ejecuta al pulsar Aplicar. Windows pedirá permiso de administrador una vez.",
    displayName: "Tu nombre",
    displayNamePlaceholder: "p. ej. Alex",
    focusOutput: "¿En qué estás trabajando?",
    focusOutputPlaceholder: "p. ej. Escribir el primer borrador",
    duration: "Duración (minutos)",
    unwindWentWell: "¿Qué salió bien hoy?",
    unwindTomorrow: "Primer paso para mañana",
    unwindTomorrowPlaceholder: "p. ej. Revisar notas a las 9",
    heroTask: "Tarea principal",
    tasksRemaining: (n) =>
      `${n} tarea${n === 1 ? "" : "s"} restante${n === 1 ? "" : "s"} hoy`,
    timeLeft: (m) => `${m}m restantes`,
    skill: "Habilidad",
    challenge: "Desafío",
    depth: "Profundidad",
    language: "Idioma",
    appearance: "Apariencia",
    themeDark: "Oscuro",
    themeLight: "Claro",
    reducedMotion: "Movimiento reducido",
    tunnelVision: "Atenuar pantalla",
    deepWorkGuard: "Modo concentración",
    blockSites: "Bloquear sitios listados durante el enfoque",
    domains: "Dominios, uno por línea",
    openWindowsFocus: "Abrir No molestar y Concentración",
    openFocusGuide: "Abrir guía de enfoque",
    sessionDisposition: "Estado de la sesión",
    done: "Hecho",
    continueLater: "Continuar después",
    nextAction: "Siguiente acción concreta",
    bestFocusHour: "Mejor hora de enfoque",
    bestTaskType: "Mejor tipo de tarea",
    averageDepth: "Profundidad media",
    completionRate: "Tasa de finalización",
    domainsPlaceholder: "youtube.com\nx.com",
    sessionMinutes: (n) => `${n} min`,
  },
  language: {
    en: "English",
    es: "Español",
  },
  compact: {
    focusing: "Enfoque",
    paused: "Pausado",
    recovery: "Descanso",
    ready: "Listo",
    currentPath: "Tarea actual",
    versionLabel: "AIBA v1.2",
    preferences: "Preferencias",
  },
  focus: {
    completed: "Completada",
    completedDuring: (duration) => `Completada en sesión · ${duration}`,
    currentFocus: "Enfoque actual",
    upNext: "Siguiente",
    pending: "Pendiente",
    skillLow: "Baja",
    skillMedium: "Media",
    skillHigh: "Alta",
    current: "Actual",
    markComplete: (task) => `Marcar ${task} como completada`,
    historyLine: (time, task, skill, challenge, isCurrent) =>
      `${time} — ${task} [Habilidad: ${skill} / Desafío: ${challenge}]${isCurrent ? " [Actual]" : ""}`,
    flowAligned: "Desafío y habilidad están alineados.",
    flowAnxiety: "Divide el resultado en un hito más pequeño.",
    flowBoredom: "Aumenta el desafío o acota el resultado.",
    recoveryHint:
      "Aparta la mirada de la pantalla. Camina, estírate o mira a lo lejos.",
  },
  focusPrep: {
    title: "Iniciar enfoque",
    emptyLead:
      "Elige una tarea en Plan y pulsa Iniciar enfoque para preparar la sesión aquí.",
    directLead:
      "Escribe en qué vas a trabajar, o ve a Plan para elegir de tus tareas.",
    goToPlan: "Ir a Plan",
    selectedTask: "Trabajando en",
    changeTask: "Cambiar tarea",
    duration: "Duración",
    durationMin: (n) => `${n} min`,
    taskType: "Tipo de tarea",
    taskTypeHint:
      "Trabajo profundo, tareas ligeras, aprendizaje o colaboración — se usa en los patrones.",
    environment: "Ajustes de sesión",
    preferencesLink: "Preferencias",
  },
  review: {
    title: "¿Qué tal fue la sesión?",
    hint: "Ayuda a calcular tus patrones de enfoque con el tiempo.",
    quality: {
      distracted: "Distraída",
      shallow: "Superficial",
      normal: "Normal",
      deep: "Profunda",
    },
    save: "Guardar sesión",
    goUnwind: "Anotar mañana en Cierre →",
    nextActionPlaceholder: "Siguiente paso (opcional)",
  },
  plan: {
    tomorrowPrompt: (step) => `De anoche: «${step}»`,
    addTomorrowStep: "Añadir como tarea",
    dismissTomorrow: "Ahora no",
    tomorrowHint:
      "Lo de anoche no pasa solo a Plan — usa esto si quieres convertirlo en tarea.",
  },
  patterns: {
    bestHourEmpty: "Necesitas 3 sesiones que empiecen a la misma hora.",
    bestTypeEmpty: "Necesitas 3 sesiones del mismo tipo de tarea.",
  },
  ask: {
    intro: "Toca una pregunta para ver la respuesta.",
    faqs: [
      { id: "morning-plan", question: "¿Para qué sirve Plan?" },
      { id: "afternoon-focus", question: "¿Cómo inicio un bloque de enfoque?" },
      { id: "evening-unwind", question: "¿Qué escribo en Unwind?" },
      { id: "sessions", question: "¿Dónde veo las sesiones pasadas?" },
      { id: "preferences", question: "¿Qué puedo cambiar en Preferencias?" },
      { id: "patterns", question: "¿Cuándo aparecen los patrones?" },
    ],
    openTool: (label) => `Ir a ${label} →`,
    openHelp: "Abrir ayuda →",
  },
  doneToday: "Hecho hoy",
  unwind: {
    sessionsToday: "Sesiones hoy",
    focusMinutes: "Tiempo de enfoque",
    tasksCompleted: "Tareas hechas",
  },
  studio: {
    title: "Aiba",
    coreIntent: "Objetivo del día",
    atelier: "Compacto",
    viewAll: "Ver todo",
    backToPlan: "Volver a Plan",
    backToPhase: "Volver",
    helloFallback: "Hola",
    helloUser: (name) => `Hola, ${name}`,
    phaseHeader: {
      morning: "Plan",
      afternoon: "Focus",
      evening: "Unwind",
    },
    todayLead: "Objetivo del día",
    todayPlaceholder: "¿Qué debería quedar hecho hoy?",
    notesLabel: "Notas",
    notesPlaceholder: "Recordatorios, pendientes, lo que tengas en mente",
    focusLead: "Objetivo del día",
    unwindLead: "Fin del día",
    focusTagline: "Una tarea a la vez.",
    restTagline: "Descansa cuando suene el temporizador.",
    eveningHeadline: "Cierra el día",
    sections: {
      today: { jp: "今日", label: "Hoy" },
      notes: { jp: "控え", label: "Notas rápidas" },
      tasks: { jp: "事", label: "Tareas" },
      history: { jp: "履歴", label: "Historial" },
      wentWell: { jp: "良", label: "Qué salió bien" },
      tomorrow: { jp: "明日", label: "Primer paso de mañana" },
    },
  },
  toast: {
    siteBlockApplied: "Bloqueo de sitios activo.",
    siteBlockRemoved: "Bloqueo de sitios eliminado.",
    defaultSitesRestored: "Lista de dominios predeterminada restaurada.",
    reducedMotionOn: "Movimiento reducido activado.",
    reducedMotionOff: "Movimiento reducido desactivado.",
    tunnelVisionOn: "La pantalla se atenuará durante el enfoque.",
    tunnelVisionOff: "Atenuación de pantalla desactivada.",
    deepWorkGuardOn: "Modo concentración listo para la próxima sesión.",
    deepWorkGuardOff: "Modo concentración desactivado.",
    blockSitesOn: "Lista de dominios visible. Pulsa Aplicar para bloquear.",
    blockSitesOff: "Opciones de bloqueo ocultas.",
    themeDark: "Tema oscuro aplicado.",
    themeLight: "Tema claro aplicado.",
  },
  guard: {
    active:
      "Modo concentración activo. Activa Enfoque de Windows para silenciar notificaciones.",
    cleanup:
      "Modo concentración detenido, pero quitar el bloqueo requiere permiso de administrador.",
    blockerFailed:
      "No se aplicó el bloqueo de sitios. El modo básico sigue disponible.",
    sitesBlocked: "Los sitios listados están bloqueados durante esta sesión.",
    helperRunning: "El bloqueo de sitios está activo.",
  },
};
